version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty@1
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:16
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=local
      - PORT=8081
      - DATABASE_URL=postgresql://postgres:Qwerty@1@db:5432/mydb
    ports:
      - "8081:8081"
    depends_on: # Removed 'condition: service_healthy'
      db :
         condition: service_healthy
      